# How to run this? -> docker-compose -f docker-compose.yaml up --abort-on-container-exit --build
version: "2"
services:
  standalone-chrome-debug:
    container_name: "standalone-chrome-debug"
    image: "selenium/standalone-chrome-debug:3.7.1-beryllium"
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm

  selenium-test-alpine-java:
    container_name: "issue-528"
    image: "issue-528:latest"
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - standalone-chrome-debug
    volumes:
      - ./images:/tmp/images
