version: "2"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    environment:
      - GRID_MAX_SESSION=100
    ports:
      - "4444:4444"
    volumes: ["/dev/shm:/dev/shm"]
    privileged: true
  chrome:
    image: selenium/node-chrome-debug
    privileged: true
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VNC_ENABLED=true
    ports:
      - "5900"
    volumes: ["/dev/shm:/dev/shm"]
  firefox:
    image: selenium/node-firefox-debug
    privileged: true
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VNC_ENABLED=true
    volumes: ["/dev/shm:/dev/shm"]
    ports:
      - "5900"