version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.13.0
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5

  selenium-hub:
    image: selenium/hub:3.13.0
    ports:
      - "4444:4444"
